# .github/workflows/ci-cd.yml
name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore src/MyApi/MyApi.csproj

      - name: Build
        run: dotnet build src/MyApi/MyApi.csproj --configuration Release

      - name: Run tests
        run: dotnet test tests/MyApi.Tests/MyApi.Tests.csproj

      - name: Docker build
        run: docker build -t myapi:latest .

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu
            rm -rf dotnet-api-devops
            git clone git@github.com:iVaHuman/dotnet-api-devops.git
            cd dotnet-api-devops
            docker compose down
            docker compose up -d --build
